services:
  alchemy-websocket-micro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alchemy-websocket-micro
    ports:
      - "8081:8081"
    environment:
      - ALCHEMY_API_KEY=u0kf8PFMt_ITyaChzHfSB
      - ALCHEMY_WS_URL=wss://eth-sepolia.g.alchemy.com/v2
      - PORT=8081
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8081/api/v1/health",
          "||",
          "exit",
          "1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - alchemy-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  alchemy-network:
    driver: bridge