# ============================================================================
# CONFIGURACIÓN PARA CREAR LOTE MICRO SERVICE
# ============================================================================
# Microservicio en Go para interactuar con el contrato LoteTracing en Sepolia
#
# VARIABLES DE ENTORNO GENERADAS:
# - SEPOLIA_RPC: https://eth-sepolia.g.alchemy.com/v2/api-key
# - SEPOLIA_WS: wss://eth-sepolia.g.alchemy.com/v2/api-key
# - PORT: 8080
# - POD_NAME: {metadata.name}
# - POD_NAMESPACE: {metadata.namespace}
#
# INSTALACIÓN:
# helm install crear-lote-micro ./k8s/microservice -f config/services/crear-lote-micro/crear-lote-micro-service-values.yaml
#
# ACTUALIZACIÓN:
# helm upgrade crear-lote-micro ./k8s/microservice -f config/services/crear-lote-micro/crear-lote-micro-service-values.yaml
# ============================================================================

replicaCount: 1

image:
  repository: crear-lote-micro
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Configuración del servicio Kubernetes
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# ============================================================================
# CONFIGURACIÓN ESPECÍFICA DE LA APLICACIÓN
# ============================================================================
# Estas variables se convierten en variables de entorno
app:
  config:
    # HTTP Server Configuration
    PORT: "8080"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "true"

podSecurityContext: {}
securityContext: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# Health checks
livenessProbe:
  enabled: true
  httpGet:
    path: /api/v1/health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /api/v1/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3

# ============================================================================
# VARIABLES DE ENTORNO ADICIONALES
# ============================================================================
env:
  # Variables comunes (incluidas automáticamente)
  common:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  # Variables personalizadas adicionales - Blockchain secrets
  custom:
    # Sepolia RPC endpoint from secret
    - name: SEPOLIA_RPC
      valueFrom:
        secretKeyRef:
          name: blockchain-secrets
          key: sepolia-rpc
    # Sepolia WebSocket endpoint from secret
    - name: SEPOLIA_WS
      valueFrom:
        secretKeyRef:
          name: blockchain-secrets
          key: sepolia-ws

# ============================================================================
# CONFIGURACIÓN DE BLOCKCHAIN
# ============================================================================
blockchain:
  # Ethereum Sepolia network configuration
  network: "sepolia"
  chainId: 11155111
  # Secret configuration for blockchain endpoints
  secretName: "blockchain-secrets"
  rpcSecretKey: "sepolia-rpc"
  wsSecretKey: "sepolia-ws"

# ============================================================================
# CARACTERÍSTICAS DESHABILITADAS PARA ESTE MICROSERVICIO
# ============================================================================
configMap:
  enabled: false

secret:
  enabled: true
  name: "blockchain-secrets"
  data:
    # These values should be created manually or via CI/CD
    # sepolia-rpc: <base64-encoded-rpc-endpoint>
    # sepolia-ws: <base64-encoded-ws-endpoint>

ingress:
  enabled: false

# ============================================================================
# CONFIGURACIÓN DE ISTIO SERVICE MESH
# ============================================================================
istio:
  enabled: true
  labels:
    app: crear-lote-micro
    version: v1

  # Virtual Service configuration (if needed)
  virtualService:
    enabled: false
    hosts: []
    gateways: []

  # Destination Rule configuration (if needed)
  destinationRule:
    enabled: false

# ============================================================================
# CONFIGURACIÓN DE MONITOREO Y OBSERVABILIDAD
# ============================================================================
monitoring:
  # Prometheus metrics
  prometheus:
    enabled: true
    port: 9090
    path: /metrics

  # Service monitor for Prometheus operator
  serviceMonitor:
    enabled: false
    labels: {}
    interval: 30s

# ============================================================================
# CONFIGURACIÓN DE PERSISTENCIA (SI SE NECESITA EN EL FUTURO)
# ============================================================================
persistence:
  enabled: false
  # storageClass: ""
  # accessMode: ReadWriteOnce
  # size: 1Gi

# ============================================================================
# CONFIGURACIÓN DE NETWORKING
# ============================================================================
networking:
  # Network policies (if needed)
  networkPolicy:
    enabled: false
    ingress: []
    egress: []

# ============================================================================
# CONFIGURACIÓN DE DESARROLLO Y DEBUG
# ============================================================================
debug:
  enabled: true
  logLevel: "DEBUG"

# ============================================================================
# CONFIGURACIÓN DE BACKUP Y RECOVERY (PARA FUTURO USO)
# ============================================================================
backup:
  enabled: false

# ============================================================================
# CONFIGURACIÓN DE TESTING
# ============================================================================
testing:
  enabled: false
  image:
    repository: curlimages/curl
    tag: latest

# ============================================================================
# ANOTACIONES Y ETIQUETAS ADICIONALES
# ============================================================================
additionalLabels:
  component: crear-lote-micro
  tier: backend
  framework: go
  blockchain: ethereum
  network: sepolia

additionalAnnotations:
  description: "Crear Lote Micro Service - Ethereum Sepolia Blockchain Integration"
  version: "1.0.0"
  maintainer: "platform-team"
  blockchain.network: "sepolia"
  blockchain.chainId: "11155111"