apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: "anonymous"
  deployment:
    cluster_wide_access: true
    replicas: 1
    view_only_mode: false
  external_services:
    prometheus:
      url: "http://prometheus-server.istio-system:80"
    grafana:
      url: "http://localhost:3000"
      in_cluster_url: "http://grafana.istio-system:80"
      auth:
        type: "basic"
        username: "secret:kiali-grafana-auth:username"
        password: "secret:kiali-grafana-auth:password"
      dashboards:
        - name: "Istio Service Dashboard"
          variables:
            datasource: "var-datasource"
            namespace: "var-namespace"
            service: "var-service"
            version: "var-version"
        - name: "Istio Workload Dashboard"
          variables:
            datasource: "var-datasource"
            namespace: "var-namespace"
            workload: "var-workload"
            version: "var-version"
        - name: "Istio Mesh Dashboard"
        - name: "Istio Control Plane Dashboard"
        - name: "Istio Performance Dashboard"
        - name: "Istio Wasm Extension Dashboard"
      datasource_uid: ""
      enabled: true
      external_url: "http://localhost:3000"
      internal_url: "http://grafana.istio-system:80"
    tracing:
      enabled: true
      internal_url: "http://tracing.istio-system:16685/jaeger"
      use_grpc: true
      # Public facing URL of Jaeger
      external_url: "http://localhost:16686/jaeger"
    istio:
      config_map_name: "istio"
      istio_sidecar_annotation: "sidecar.istio.io/status"
      url_service_version: "http://istiod.istio-system:15014/version"
  version: "default"