apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-service-scaler
  namespace: mediorder
  labels:
    app: order-service
    component: autoscaler
spec:
  scaleTargetRef:
    name: order-service-microservice
  minReplicaCount: 1
  maxReplicaCount: 2
  pollingInterval: 15
  cooldownPeriod: 150
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-warehouse-controller-0.kafka-warehouse-controller-headless.mediwarehouse.svc.cluster.local:9092
        consumerGroup: warehouse-batch-service
        topic: warehouse-order-events
        lagThreshold: "300"
        offsetResetPolicy: earliest